[package]
name = "sez-audio"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
cpal.workspace = true
rubato.workspace = true
sez-core = { path = "../sez-core" }
thiserror.workspace = true

[dev-dependencies]
sez-core = { path = "../sez-core", features = ["test-util"] }
tokio.workspace = true
